INSERT INTO products VALUES ("CodProdus1","Iphone","iphone description",10,1050.99);
INSERT INTO products VALUES ("CodProdus2","Mac Book","macbook description",20,4240.50);
INSERT INTO products VALUES ("CodProdus3","Telefon Samsung","samsung description",14,945.80);
INSERT INTO products VALUES ("CodProdus4","Ebook reader","ebook reader description",20,555.90);
INSERT INTO products VALUES ("CodProdus5","Wireless keyboard","Wireless keyboard description",5,243.60);
INSERT INTO products VALUES ("CodProdus6","Smart Watch","smart watch description",9,1140.45);
INSERT INTO products VALUES ("CodProdus7","Usb cable","usb cable description",15,50.55);
INSERT INTO products VALUES ("CodProdus8","Carcasa pc","carcasa pc description",20,300.99);
INSERT INTO products VALUES ("CodProdus9","Cooler","cooler description",30,210.50);
INSERT INTO products VALUES ("CodProdus10","Graphic card","graphic card description",12,1545.50);